#include <iostream>
#include <stdlib.h>
#include <limits.h>

#include "EVRP.hpp"
#include "heuristic.hpp"
#include "stats.hpp"

using namespace std;

/*initialiazes a run for your heuristic*/
void start_run()
{

  init_evals();
  init_current_best();
}

/*gets an observation of the run for your heuristic*/
void end_run(int r)
{

  get_mean(r - 1, get_current_best()); // from stats.h
  cout << "End of run " << r << " with best solution quality " << get_current_best() << " total evaluations: " << get_evals() << endl;
  cout << " " << endl;
}

/*sets the termination conidition for your heuristic*/
bool termination_condition(void)
{

  bool flag;
  if (get_evals() >= TERMINATION)
    flag = true;
  else
    flag = false;

  return flag;
}

/****************************************************************/
/*                Main Function                                 */
/****************************************************************/
int main(int argc, char *argv[])
{

  int run;

  /*Step 1*/
  problem_instance = argv[1]; // pass the .evrp filename as an argument
  mutation_rate = stof(argv[2]);
  crossover_rate = stof(argv[3]);
  mutation_method = argv[4];
  select_pres = stof(argv[5]);
  n_pop = stoi(argv[6]);

  if (argc < 2)
  {
    cerr << "Uso: " << argv[0]
         << " <metodo_de_mutacao>" << endl;

    cerr << "Métodos disponíveis:" << endl;
    cerr << "  ins - mutação por inserção" << endl;
    cerr << "  mix - mutação por mistura" << endl;
    cerr << "  inv - mutação por inversão" << endl;

    return 1;
  }

  if (mutation_method != "ins" &&
      mutation_method != "mix" &&
      mutation_method != "inv")
  {
    cerr << "Mutation method not implemented: "
         << mutation_method << endl;

    return 1;
  }

  cout << "===== SELECTED PARAMETERS =====" << endl;
  cout << "Instance file:      " << problem_instance << endl;
  cout << "Mutation rate:      " << mutation_rate << endl;
  cout << "Crossover rate:     " << crossover_rate << endl;
  cout << "Mutation method:   " << mutation_method << endl;
  cout << "Selection pressure: " << select_pres << endl;
  cout << "Population size:    " << n_pop << endl;
  cout << "================================" << endl
       << endl;

  read_problem(problem_instance); // Read EVRP from file from EVRP.h

  
  /*Step 2*/
  open_stats(); // open text files to store the best values from the 20 runs stats.h
  
  for (run = 1; run <= MAX_TRIALS; run++)
  {
    /*Step 3*/
    start_run();

    // Initialize your heuristic here
    initialize_heuristic(run); // heuristic.h

    /*Step 4*/
    while (!termination_condition())
    {
      // Execute your heuristic
      run_heuristic(); // heuristic.h
    }

    // print_solution(best_sol->tour, best_sol->steps);

    write_solution(best_sol->tour, best_sol->steps);

    // check_solution(best_sol->tour,best_sol->steps);

    /*Note that the solution generated by the random heuristic may not
    be feasisble in terms of energy when check_solution is utilized.

    The implementation is only for your reference*/
    /*Step 5*/
    end_run(run); // store the best solution quality for each run
  }

  /*Step 6*/
  close_stats(); // close text files to calculate the mean result from the 20 runs stats.h

  // free memory
  free_stats();
  free_heuristic();
  free_EVRP();

  cout << R"(
  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::---------
  ::::::::::::::::::::::::::::::::::           THE END           ::::::::::::::::::::::::::::::----------
  :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::+%%*--------
  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*#+::::::::=#%#:::::::::::::#@@@@--------
  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::-@@@@*::::::#@@@@+::::::::::::-@@@@+-------
  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::#@@@@*::::::%@@@@*:::::::::::::@@%*--------
  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::@@@@::::::::::@@@@=::::::::::::%@@@@*:-------
  :::::::::::::::::::::::::::::::::::::::::::::::%@@%::::::@@@@@@:::::::=@@@@@@-:::::::::::@@@@@@*:------
  ::::::::::::::::::::::::::::::::::::::::::::+@@@@@@-:::::@@@@@@:::::::@@@@@@@%:::::::::::%@@@@@%-------
  :::::::::::::::::::::::::::::::::::#@@:::::@@@@@@@@@:::::%@@@@=:::::::@@@@@@@@:::::::::::@@@@@@@-:-----
  ::::::::::::::::::::::::::::::*@@@@@@@@:::@@@@@@:::::::::@@@@@-:::::::@@@@@@@#::::::::::-@@@@@@@@=::---
  ::::::::::::::::::::::::::@@@@@@@@@@%@@::%@@@@@@:::::::::@@@@@@*::::::@@@@@@@@-::::::::::@@@@@@#-#@=::-
  ::::::::::::::::::::::::+@@@@@@@@@@#:::::@@@@@@@::::::::+@@@@@==#:::::#@@@@@@%%#::::::::-@@@@@@%:--@=--
  ::::::::::-%@@@%:::::::#@@@@@@@@@@@@::::-@@@@@@@=::::::::@@@@@@%:::::::@@@@@@%-@-:::::::+@@@@@@@%------
  ::::::+@@@@@@@@@#:::::*@@@@@@@%%@@@-:::::@@@@@@@@+::::::::@@@@@@%:::::-@@@@@@@@-::::::::=%@@@@@@@#-----
  ::::#@@@@@@@@@@::::::::%@@@@@@+#@@-::::::%@@@@@@@@:::::::-@@@@@@@=:::::%@@@@@@@*:::::::::-@@@#@@@@-----
  :::%@@@@@@@@@@@%:::::::=@@@@@@@@@@#:::::::%@@@@@@@-:::::::@@@##@@*:::::@@@*:#@@@:::::::::*@@%--*@@@----
  :::@@@@@@%:-@@@@%:::::::%@@@@*%@@@@:::::::+@@@@@@@:::::::%@@%::@@@:::::@@@=:*@@*:::::::-%@@%----%@@=---
  :::@@@@@@@:::%@@@@%:::::%@@@#:%@@-:@%:::::+@@@=%@@%::::#@@@*::%@@#::::%@@+::*@@=::::::+@@@=:::--@@@=---
  :::%@@@#@@@::::@%::#*:+@@@@#::@@@:::+::*@@@@@-:%@@@:::%@@@::::@@@:::::@@%:::+@@:::::::@@*:::::::+@@*---
  ::@@@*::%@@:::::**:::%@@%-::::@@#:::::@@@@*:::::@@@::-@@=:::::%@+:::::@@:::::%@:::::=@%:::::::::-=@@---
  %#%@#+#%@@@+**+-*@+-*@@-:--:+*@@++-+=@@#=::::===#@@%*@@@###=:=%@@*###%@@+=#+##@@%%+%@@%%#%######@#@@@%%
  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  )";

  return 0;
}
